version: '3.8'
services:
  app:
    build: .
    container_name: simple_webapp
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    ports:
      - "3000:3000"
      - "5000:5000"
    depends_on:
      - mongo
    volumes:
      - ./storage:/app/storage
  mongo:
    image: mongo:6.0
    container_name: simple_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: